/*****************************************************************************
 *
 *	VERSION:	%W%	%E%
 *
 *      IN PACKAGE:	TASKING Peripheral Library for 80515
 *
 *      AUTHORS:        SAPA
 *
 *      COPYRIGHT:	Copyright (c) 2003, Altium BV
 *
 *      DESCRIPTION:	General include file for the Peripheral Library 
 *			for 80515.
 *			Include this file in modules that uses functions 
 *			from the Peripheral Library. 
 *
 *			Headerfile "tealib_cfg.h", usually located in the 
 *			user's project directory, tells which peripherals are 
 *			involved and thus needs to be included. 
 *
 ****************************************************************************/


/*
 * Do NOT edit this file!!!
 */



/*
 * Include library configuration file, e.g. which peripherals are used.
 */
#include "tealib_cfg.h"

#ifdef UART0
#include "uart_types.h"
#include "uart0.h"
#endif
#ifdef UART1
#include "uart_types.h"
#include "uart1.h"
#endif

#ifdef CAN0
#include "can0.h"
#endif

#ifdef I2C0
#include "i2c0.h"
#endif


#if (defined TMR0) && (defined CNT0)
//#error > Cannot use timer/counter 0 as timer and counter simultaneously
#endif

#if (defined TMR1) && (defined CNT1)
//#error > Cannot use timer/counter 1 as timer and counter simultaneously
#endif


#ifdef TMR0
#include "timer0.h"
#endif
#ifdef TMR1
#include "timer1.h"
#endif


#ifdef CNT0
#include "counter0.h"
#endif
#ifdef CNT1
#include "counter1.h"
#endif

#ifdef KEYB0
#include "keyb0.h"
#endif

#ifdef MOUSE0
#include "mouse0.h"
#endif

#ifdef VGA0
#include "vga0.h"
#endif

#ifdef LCD0
#include "lcd0.h"
#endif

#ifdef KEYMATRIX0
#include "keymatrix0.h"
#endif
