/*****************************************************************
**
** File         : fsdef.h
** Function     : settings for diskimage
**
** Generated at : 2003/12/19 16:07:17
** Generated by : makediskimg v1.1
**
** MANUAL CHANGES WILL BE OVERWRITTEN IF THIS FILE IS RE-GENERATED
**
******************************************************************/

#ifndef FILESYSTEM_PROPERTIES_H
#define FILESYSTEM_PROPERTIES_H

#define FS_DISKSIZE 0x2000 // (8192)
#define FS_CLUSTERSIZE 0x80 // (128)
#define FS_ROOTENTRIES 0x40 // (64)
#define FS_MAXFILENAMELEN 9
#define FS_ENTRY_FORMAT "BFFFFCCSNNNNNNNNN"

#endif

