/*****************************************************************
**
** File         : httpdef.h
** Function     : settings for HTTP server
**
** Generated at : 2003/12/19 16:07:17
** Generated by : stackconfmake v1.1
**
** MANUAL CHANGES WILL BE OVERWRITTEN IF THIS FILE IS RE-GENERATED
**
******************************************************************/


// variables accessed by the http server
extern Uint16 temperature_cgi;
extern Uint16 temperature_threshold_cgi;
extern Uint8 led_red_cgi;
extern Uint8 led_yellow_cgi;
extern Uint16 seconds_cgi;
extern Uint16 minutes_cgi;
extern Uint16 hours_cgi;
extern Uint16 days_cgi;

// include hardcoded pages
#include "httpdef_fixed.h"

// urls for CGI interface
#define HTTP_CGIURL_GET "/cgi/get"
#define HTTP_CGIURL_SET "/cgi/set"
#define HTTP_CGIURL_INFO "/cgi/info"

// turn on read/write code for cgivars
#define HTTP_CGIVAR_WORD
// #define HTTP_CGIVAR_STRING
#define HTTP_CGIVAR_BOOL

// turn off unused server CGI support
// #undef HTTP_CGI_GET
// #undef HTTP_CGI_SSIGET
// #undef HTTP_CGI_INFOGET
// #undef HTTP_CGI_SET

// mime types
#define HTTP_MIMETYPES \
{ \
    {"txt", "text/plain"}, \
    {"html", "text/html"}, \
    {"htm", "text/html"}, \
    {"gif", "image/gif"}, \
    {"jpeg", "image/jpeg"}, \
    {"jpg", "image/jpeg"}, \
    {"jar", "application/java"}, \
    {0, NULL} \
}

// CGI variable access definitions
#define HTTP_SSIGETVAR_MAXLEN 21
#define HTTP_CGIVARS \
{ \
    {0|HTTP_CGI_GET|HTTP_CGI_SSIGET|HTTP_CGI_INFOGET, &temperature_cgi, "temperature", (ROMMEMSPEC void*) 0, (ROMMEMSPEC void*) 1024, &cgifunc_word}, \
    {0|HTTP_CGI_GET|HTTP_CGI_SSIGET|HTTP_CGI_INFOGET|HTTP_CGI_SET, &temperature_threshold_cgi, "temperature-threshold", (ROMMEMSPEC void*) 0, (ROMMEMSPEC void*) 1024, &cgifunc_word}, \
    {0|HTTP_CGI_GET|HTTP_CGI_SSIGET|HTTP_CGI_INFOGET|HTTP_CGI_SET, &led_red_cgi, "led-red", (ROMMEMSPEC void*) "off", (ROMMEMSPEC void*) "on", &cgifunc_bool}, \
    {0|HTTP_CGI_GET|HTTP_CGI_SSIGET|HTTP_CGI_INFOGET, &led_yellow_cgi, "led-yellow", (ROMMEMSPEC void*) "dark", (ROMMEMSPEC void*) "yellow", &cgifunc_bool}, \
    {0|HTTP_CGI_GET|HTTP_CGI_SSIGET|HTTP_CGI_INFOGET, &seconds_cgi, "seconds-cgi", (ROMMEMSPEC void*) 0, (ROMMEMSPEC void*) 0, &cgifunc_word}, \
    {0|HTTP_CGI_GET|HTTP_CGI_SSIGET|HTTP_CGI_INFOGET, &minutes_cgi, "minutes-cgi", (ROMMEMSPEC void*) 0, (ROMMEMSPEC void*) 0, &cgifunc_word}, \
    {0|HTTP_CGI_GET|HTTP_CGI_SSIGET|HTTP_CGI_INFOGET, &hours_cgi, "hours-cgi", (ROMMEMSPEC void*) 0, (ROMMEMSPEC void*) 0, &cgifunc_word}, \
    {0|HTTP_CGI_GET|HTTP_CGI_SSIGET|HTTP_CGI_INFOGET, &days_cgi, "days-cgi", (ROMMEMSPEC void*) 0, (ROMMEMSPEC void*) 0, &cgifunc_word}, \
    {0, 0, 0, 0, 0} \
}

