/*****************************************************************
**
** File         : fsdef.h
** Function     : settings for diskimage
**
** Generated at : 2003/08/29 12:29:01
** Generated by : makediskimg v0.1
**
** MANUAL CHANGES WILL BE OVERWRITTEN IF THIS FILE IS RE-GENERATED
**
******************************************************************/

#ifndef FILESYSTEM_PROPERTIES_H
#define FILESYSTEM_PROPERTIES_H

#define FS_DISKSIZE 0x20000 // (131072)
#define FS_CLUSTERSIZE 0x200 // (512)
#define FS_ROOTENTRIES 0x40 // (64)
#define FS_MAXFILENAMELEN 17
#define FS_ENTRY_FORMAT "BFFFFCCSNNNNNNNNNNNNNNNNN"

#endif

