/*****************************************************************
**
** File         : httpdef.h
** Function     : settings for HTTP server
**
** Generated at : 2003/08/29 12:29:01
** Generated by : stackconfmake v0.1
**
** MANUAL CHANGES WILL BE OVERWRITTEN IF THIS FILE IS RE-GENERATED
**
******************************************************************/


// variables accessed by the http server

// urls for CGI interface
#define HTTP_CGIURL_GET "/cgi/get"
#define HTTP_CGIURL_SET "/cgi/set"
#define HTTP_CGIURL_INFO "/cgi/info"

// turn on read/write code for cgivars
// #define HTTP_CGIVAR_WORD
// #define HTTP_CGIVAR_STRING
// #define HTTP_CGIVAR_BOOL

// turn off unused server CGI support
#undef HTTP_CGI_GET
#undef HTTP_CGI_SSIGET
#undef HTTP_CGI_INFOGET
#undef HTTP_CGI_SET

// mime types
#define HTTP_MIMETYPES \
{ \
    {"txt", "text/plain"}, \
    {"html", "text/html"}, \
    {"htm", "text/html"}, \
    {"gif", "image/gif"}, \
    {"jpeg", "image/jpeg"}, \
    {"jpg", "image/jpeg"}, \
    {"png", "image/png"}, \
    {0, NULL} \
}

// CGI variable access definitions
// #define HTTP_SSIGETVAR_MAXLEN 0
// #define HTTP_CGIVARS \
// { \
//     {0, 0, 0, 0, 0} \
// }

