/* include bitmaps */

#include "altium16.c"
#include "direction.c"
#include "speed.c"
#include "temp_c.c"
#include "50.c"
#include "40.c"
#include "30.c"
#include "20.c"
#include "10.c"
#include "zero.c"
#include "-10.c"
#include "-20.c"
#include "north.c"
#include "east.c"
#include "south.c"
#include "west.c"
#include "0h.c"
#include "-2h.c"
#include "-4h.c"
#include "-6h.c"
#include "-8h.c"
#include "-10h.c"
#include "-12h.c"
#include "-14h.c"
#include "-16h.c"
#include "-18h.c"
#include "-20h.c"
#include "-22h.c"
#include "-24h.c"

